name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # Windows throws false positives with linting because of CRLF
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Start xvfb for ubuntu tests
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: /usr/bin/Xvfb :99 -screen 0 1024x768x24

      - name: Run tests
        run: npm run test
        env:
          DISPLAY: ':99.0'